version: '3.7'

services:

  sample:
    container_name: react-storybook-ctn
    build:
      context: .
      dockerfile: src/Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
  doc_storybook:
    container_name: doc_storybook
    build:
      context: .
      dockerfile: .storybook/Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - "6006:6006"
    environment:
      - CHOKIDAR_USEPOLLING=true